<?php

/**
 * Pivotal Analytics Init Script
 *
 * @category    Analytics
 * @package     Pivotal_Analytics
 * @author      Ankit Patel <ankit.patel@pivotal.digital>
 * @var $block \Pivotal\Analytics\Block\js
 * @var \Magento\Framework\Escaper $escaper */

$functionItentifier = \Pivotal\Analytics\Helper\Data::PIVOTAL_ANALYTICS_FUNCTION_IDENTIFIER;
$siteKey = $escaper->escapeHtml($block->getSiteKey());
$url = "https://$functionItentifier.functions.supabase.co/pivotal-analytics?key=$siteKey&v=v4.1";
?>

<script>
    (function(p, v, t) {
        p.pivotalQ = p.pivotalQ || [];
        var f = v.getElementsByTagName(t)[0],
            j = v.createElement(t);
        j.async = 1;
        j.src = <?= /* @noEscape */ $url ?>;
        f.parentNode.insertBefore(j, f);
    })(window, document, 'script');
</script>